controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\MainController::index

#Yaml for Post paths
createPost:
    path: /post/create
    controller: App\Controller\PostController::create
    methods: [POST]

selectOnePost:
    path: /post/show/{id}
    controller: App\Controller\PostController::show
    methods: [GET]

selectAllPosts:
    path: /post/showAll
    controller: App\Controller\PostController::showAll
    methods: [GET]

updatePost:
    path: /post/update/{id}
    controller: App\Controller\PostController::update
    methods: [POST]

removePost:
    path: /post/remove
    controller: App\Controller\PostController::remove

#Yaml for Comment paths
createComment:
    path: /comment/create
    controller: App\Controller\CommentController::create
    methods: [POST]