controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\MainController::index

#Yaml for Post paths
createPost:
    path: /post/create
    controller: App\Controller\PostController::create
    methods: [POST]

selectOnePost:
    path: /post/show/{id}
    controller: App\Controller\PostController::show
    methods: [GET]

selectAllPosts:
    path: /post/showall
    controller: App\Controller\PostController::showAll
    methods: [GET]

updatePost:
    path: /post/update/{id}
    controller: App\Controller\PostController::update
    methods: [POST]

removePost:
    path: /post/remove/{id}
    controller: App\Controller\PostController::remove
    methods: [DELETE]

#Yaml for Comment paths
createComment:
    path: /comment/create
    controller: App\Controller\CommentController::create
    methods: [POST]

showAllComments:
    path: /comment/showall
    controller: App\Controller\CommentController::showAll
    methods: [GET]

updateComment:
    path: /comment/update/{id}
    controller: App\Controller\CommentController::update
    methods: [POST]

deleteComment:
    path: /comment/remove/{id}
    controller: App\Controller\CommentController::remove
    methods: [DELETE]