controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\MainController::index

#Yaml for Post paths
createPost:
    path: /post/create
    controller: App\Controller\PostController::create
    methods: [POST]

selectOnePost:
    path: /post/show/{id}
    controller: App\Controller\PostController::show
    methods: [GET]

selectAllPosts:
    path: /post/showall
    controller: App\Controller\PostController::showAll
    methods: [GET]

updatePost:
    path: /post/update/{id}
    controller: App\Controller\PostController::update
    methods: [PUT]

removePost:
    path: /post/remove/{id}
    controller: App\Controller\PostController::remove
    methods: [DELETE]

upvotePost:
    path: /post/{id}/upvote
    controller: App\Controller\PostController::upvotePost
    methods: [POST]

#Yaml for Comment paths
createComment:
    path: /post/{postId}/comment/create
    controller: App\Controller\CommentController::create
    methods: [POST]

showOneComment:
    path: /post/{postId}/comment/showone/{id}
    controller: App\Controller\CommentController::showOne
    methods: [GET]

showAllComments:
    path: /post/{postId}/comment/showall
    controller: App\Controller\CommentController::showAll
    methods: [GET]

updateComment:
    path: /post/{postId}/comment/update/{id}
    controller: App\Controller\CommentController::update
    methods: [PUT]

deleteComment:
    path: /post/comment/remove/{id}
    controller: App\Controller\CommentController::remove
    methods: [DELETE]